# Generated by Django 4.1.3 on 2022-11-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(blank=True)),
                ('number_pages', models.IntegerField()),
                ('price', models.FloatField(null=True)),
                ('sizes', models.IntegerField()),
                ('date_publication', models.DateField()),
            ],
        ),
    ]
