# Generated by Django 4.1.3 on 2022-11-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='cover_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
