# Generated by Django 4.1.3 on 2022-12-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0003_library_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['name'], 'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='library',
            name='cover_type',
            field=models.TextField(blank=True, null=True, verbose_name='Тип обожки книги'),
        ),
        migrations.AlterField(
            model_name='library',
            name='date_publication',
            field=models.DateField(verbose_name='Дата публикации книги'),
        ),
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=120, null=True, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='library',
            name='number_pages',
            field=models.IntegerField(verbose_name='Количество страниц в книге'),
        ),
        migrations.AlterField(
            model_name='library',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография книги'),
        ),
        migrations.AlterField(
            model_name='library',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена книги'),
        ),
        migrations.AlterField(
            model_name='library',
            name='sizes',
            field=models.TextField(verbose_name='Размер книги'),
        ),
    ]
