# Generated by Django 4.1.3 on 2022-12-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0004_alter_library_options_alter_library_cover_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=120, null=True, verbose_name='Имя автора')),
                ('firstname', models.CharField(max_length=120, null=True, verbose_name='Фамилия автора')),
                ('lastname', models.CharField(max_length=120, null=True, verbose_name='Отчество автора')),
                ('biograf', models.TextField(blank=True, verbose_name='Биография автора')),
                ('photo', models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Портрет автора')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения автора')),
                ('date_of_death', models.DateField(null=True, verbose_name='Дата смерти автора')),
            ],
            options={
                'verbose_name': 'Автор книги',
                'verbose_name_plural': 'Авторы книг',
            },
        ),
        migrations.AddField(
            model_name='library',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Boormag.author', verbose_name='Автор книги'),
        ),
    ]
