# Generated by Django 4.1.3 on 2022-12-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0005_author_library_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='librarys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Boormag.library', verbose_name='Написаннные книги, имеющиеся в наличии'),
        ),
    ]
