# Generated by Django 4.1.3 on 2022-12-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0006_author_librarys'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_death2',
            field=models.CharField(max_length=120, null=True, verbose_name='Дата смерти автора'),
        ),
    ]
