# Generated by Django 4.1.3 on 2022-12-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0007_author_date_of_death2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death2',
            field=models.CharField(choices=[('По сей день', 'По сей день')], default='По сей день', max_length=120),
        ),
    ]
