# Generated by Django 4.1.3 on 2022-12-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0010_alter_author_date_of_death2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='librarys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boormag.library', verbose_name='Написаннные книги, имеющиеся в наличии'),
        ),
    ]
