# Generated by Django 4.1.3 on 2022-12-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0012_alter_library_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='librarys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Boormag.library', verbose_name='Написаннные книги, имеющиеся в наличии'),
        ),
        migrations.AlterField(
            model_name='library',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Boormag.author', verbose_name='Автор книги'),
        ),
    ]
