# Generated by Django 4.1.3 on 2022-12-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0013_alter_author_librarys_alter_library_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_death2',
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.TextField(null=True, verbose_name='Дата смерти автора'),
        ),
    ]
