# Generated by Django 4.1.3 on 2022-12-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0014_remove_author_date_of_death2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='librarys',
            field=models.TextField(null=True, verbose_name='Написаннные книги'),
        ),
    ]
