# Generated by Django 4.1.3 on 2023-02-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0015_alter_author_librarys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(default='library', max_length=120, null=True, verbose_name='Название книги'),
        ),
    ]
