# Generated by Django 4.1.3 on 2023-02-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boormag', '0016_alter_library_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boormag.author', verbose_name='Автор книги'),
        ),
    ]
