# Generated by Django 4.1.3 on 2023-02-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_status_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Отменён', 'Отменён'), ('Согласован', 'Согласован'), ('В пути', 'В пути'), ('Завершён', 'Завершён')], max_length=150, null=True, verbose_name='Статус'),
        ),
    ]
